TAURUS_CONFIG_PATH ?= ~/.config/vega-tools/settings.mk

include $(TAURUS_CONFIG_PATH)

ifndef TAURUS_SDK
$(error TAURUS_SDK not set.)
endif


EXECUTABLE_NAME=led_toggle

include $(TAURUS_SDK)/bsp/common/config.mk